### ISSUE TITLE
IOnPlayerClaim(ed)Territory missing points

### ISSUE THREAD

**Issue by pelikaanjpeg** [theumod/uMod.Hurtworld#59]
I noticed that the hook (IOnPlayerClaimTerritory and IOnPlayerClaimedTerritory) in the game itself gets called with the points included but then the override of the method doesn't include the points.
Might be an oversight or something which has been done deliberately, but I myself can't see the reasoning behind it other that it being missed.

**Comment by lukespragg** [comment]
Both of those are internal hooks, not the actual hooks. The "I" = internal; the actual hooks are called inside of those wrappers.

**Comment by pelikaanjpeg** [comment]
Oh yeah I also just noticed it was actually there, just renamed, sorry about that one. Got confused because of the casts to object so didn't really stand out as the points in the first place.
