### ISSUE TITLE
New Hotfix 0.7.0.9 Is Live!

### ISSUE THREAD

**Issue by lyskaczu** [theumod/uMod.Hurtworld#60]
Today new update from HURTWORLD, and oxide dosent work.

Thanks for oxide update.

**Comment by Mrocznv** [comment]
Just wait for it...
https://umod.org/faq#when-will-x-game-be-updated

**Comment by Slut** [comment]
Wulf is sleeping so you'll have to wait a few hours.

**Comment by pim-moeskops** [comment]
The GitHub issues are not used for discussions, please use the forums on https://umod.org/!
