### ISSUE TITLE
return Code 0 on WebRequests

### ISSUE THREAD

**Issue by igore13** [theumod/uMod.Hurtworld#62]
I tested url on https://apitester.com/ and return correct (code 200 and result 1)

and test in plugin and return code 0.

```
float timeout = 200f;
WebRequests webrequest = new WebRequests();
webrequest.Enqueue("https://hurtworld-servers.net/api/?object=votes&element=claim&key=0iJ0dKS9xtQZmi4wATD0DvnRHd3oBZwLwj&steamid=76561197985207133", null, (code, response) => GetCallback(code, response, player), this, RequestMethod.GET, null, timeout);
```

**Comment by lukespragg** [comment]
The version of mono that games such as Rust uses will not work with a lot of modern HTTPS technology such as TLS 1.3 (often 1.2 as well) and various certificate types such as ECDSA. This error isn’t really fixable outside of not using HTTPS else waiting for our standalone webclient.

**Comment by igore13** [comment]
I try with HTTP and good result, Thanks !
